export const COUNTRIES = {
    ax: {
        title: 'Åland',
        ccc: '+358',
        flag: '🇦🇽',
        translations: { en: 'Åland Islands', ar: 'جزر أولان' },
    },
    as: {
        title: 'American Samoa',
        ccc: '+1684',
        flag: '🇦🇸',
        translations: { en: 'American Samoa', ar: 'ساموا الأمريكية' },
    },
    ad: {
        title: 'Andorra',
        ccc: '+376',
        flag: '🇦🇩',
        translations: { en: 'Andorra', ar: 'أندورا' },
    },
    ao: {
        title: 'Angola',
        ccc: '+244',
        flag: '🇦🇴',
        translations: { en: 'Angola', ar: 'أنجولا' },
    },
    ai: {
        title: 'Anguilla',
        ccc: '+1264',
        flag: '🇦🇮',
        translations: { en: 'Anguilla', ar: 'أنجويلا' },
    },
    ag: {
        title: 'Antigua and Barbuda',
        ccc: '+1268',
        flag: '🇦🇬',
        translations: { en: 'Antigua and Barbuda', ar: 'أنتيجوا وبربودا' },
    },
    ar: {
        title: 'Argentina',
        ccc: '+54',
        flag: '🇦🇷',
        translations: { en: 'Argentina', ar: 'الأرجنتين' },
    },
    aw: {
        title: 'Aruba',
        ccc: '+297',
        flag: '🇦🇼',
        translations: { en: 'Aruba', ar: 'آروبا' },
    },
    au: {
        title: 'Australia',
        ccc: '+61',
        flag: '🇦🇺',
        translations: { en: 'Australia', ar: 'أستراليا' },
    },
    az: {
        title: 'Azərbaycan',
        ccc: '+994',
        flag: '🇦🇿',
        translations: { en: 'Azerbaijan', ar: 'أذربيجان' },
    },
    bs: {
        title: 'Bahamas',
        ccc: '+1242',
        flag: '🇧🇸',
        translations: { en: 'Bahamas', ar: 'الباهاما' },
    },
    bd: {
        title: 'Bangladesh',
        ccc: '+880',
        flag: '🇧🇩',
        translations: { en: 'Bangladesh', ar: 'بنجلاديش' },
    },
    bb: {
        title: 'Barbados',
        ccc: '+1246',
        flag: '🇧🇧',
        translations: { en: 'Barbados', ar: 'بربادوس' },
    },
    be: {
        title: 'België',
        ccc: '+32',
        flag: '🇧🇪',
        translations: { en: 'Belgium', ar: 'بلجيكا' },
    },
    bz: {
        title: 'Belize',
        ccc: '+501',
        flag: '🇧🇿',
        translations: { en: 'Belize', ar: 'بليز' },
    },
    bj: {
        title: 'Bénin',
        ccc: '+229',
        flag: '🇧🇯',
        translations: { en: 'Benin', ar: 'بنين' },
    },
    bm: {
        title: 'Bermuda',
        ccc: '+1441',
        flag: '🇧🇲',
        translations: { en: 'Bermuda', ar: 'برمودا' },
    },
    bo: {
        title: 'Bolivia',
        ccc: '+591',
        flag: '🇧🇴',
        translations: { en: 'Bolivia', ar: 'بوليفيا' },
    },
    bq: {
        title: 'Bonaire',
        ccc: '+599',
        flag: '🇧🇶',
        translations: { en: 'Caribbean Netherlands', ar: 'بونير' },
    },
    ba: {
        title: 'Bosna i Hercegovina',
        ccc: '+387',
        flag: '🇧🇦',
        translations: { en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
    },
    bw: {
        title: 'Botswana',
        ccc: '+267',
        flag: '🇧🇼',
        translations: { en: 'Botswana', ar: 'بتسوانا' },
    },
    bv: {
        title: 'Bouvetøya',
        ccc: '+47',
        flag: '🇧🇻',
        translations: { en: 'Bouvet Island', ar: 'جزيرة بوفيه' },
    },
    br: {
        title: 'Brasil',
        ccc: '+55',
        flag: '🇧🇷',
        translations: { en: 'Brazil', ar: 'البرازيل' },
    },
    io: {
        title: 'British Indian Ocean Territory',
        ccc: '+246',
        flag: '🇮🇴',
        translations: {
            en: 'British Indian Ocean Territory',
            ar: 'المحيط الهندي البريطاني',
        },
    },
    vg: {
        title: 'British Virgin Islands',
        ccc: '+1284',
        flag: '🇻🇬',
        translations: { en: 'British Virgin Islands', ar: 'جزر فرجين البريطانية' },
    },
    bf: {
        title: 'Burkina Faso',
        ccc: '+226',
        flag: '🇧🇫',
        translations: { en: 'Burkina Faso', ar: 'بوركينا فاسو' },
    },
    bi: {
        title: 'Burundi',
        ccc: '+257',
        flag: '🇧🇮',
        translations: { en: 'Burundi', ar: 'بوروندي' },
    },
    cv: {
        title: 'Cabo Verde',
        ccc: '+238',
        flag: '🇨🇻',
        translations: { en: 'Cape Verde', ar: 'الرأس الأخضر' },
    },
    cm: {
        title: 'Cameroon',
        ccc: '+237',
        flag: '🇨🇲',
        translations: { en: 'Cameroon', ar: 'الكاميرون' },
    },
    ky: {
        title: 'Cayman Islands',
        ccc: '+1345',
        flag: '🇰🇾',
        translations: { en: 'Cayman Islands', ar: 'جزر الكايمن' },
    },
    cz: {
        title: 'Česká republika',
        ccc: '+420',
        flag: '🇨🇿',
        translations: { en: 'Czechia', ar: 'جمهورية التشيك' },
    },
    cl: {
        title: 'Chile',
        ccc: '+56',
        flag: '🇨🇱',
        translations: { en: 'Chile', ar: 'شيلي' },
    },
    co: {
        title: 'Colombia',
        ccc: '+57',
        flag: '🇨🇴',
        translations: { en: 'Colombia', ar: 'كولومبيا' },
    },
    ck: {
        title: 'Cook Islands',
        ccc: '+682',
        flag: '🇨🇰',
        translations: { en: 'Cook Islands', ar: 'جزر كوك' },
    },
    cr: {
        title: 'Costa Rica',
        ccc: '+506',
        flag: '🇨🇷',
        translations: { en: 'Costa Rica', ar: 'كوستاريكا' },
    },
    ci: {
        title: "Côte d'Ivoire",
        ccc: '+225',
        flag: '🇨🇮',
        translations: { en: 'Ivory Coast', ar: 'ساحل العاج' },
    },
    cu: {
        title: 'Cuba',
        ccc: '+53',
        flag: '🇨🇺',
        translations: { en: 'Cuba', ar: 'كوبا' },
    },
    cw: {
        title: 'Curaçao',
        ccc: '+5999',
        flag: '🇨🇼',
        translations: { en: 'Curaçao', ar: 'كوراساو' },
    },
    dk: {
        title: 'Danmark',
        ccc: '+45',
        flag: '🇩🇰',
        translations: { en: 'Denmark', ar: 'الدانمرك' },
    },
    de: {
        title: 'Deutschland',
        ccc: '+49',
        flag: '🇩🇪',
        translations: { en: 'Germany', ar: 'ألمانيا' },
    },
    dj: {
        title: 'Djibouti',
        ccc: '+253',
        flag: '🇩🇯',
        translations: { en: 'Djibouti', ar: 'جيبوتي' },
    },
    dm: {
        title: 'Dominica',
        ccc: '+1767',
        flag: '🇩🇲',
        translations: { en: 'Dominica', ar: 'دومينيكا' },
    },
    ec: {
        title: 'Ecuador',
        ccc: '+593',
        flag: '🇪🇨',
        translations: { en: 'Ecuador', ar: 'الاكوادور' },
    },
    ee: {
        title: 'Eesti',
        ccc: '+372',
        flag: '🇪🇪',
        translations: { en: 'Estonia', ar: 'استونيا' },
    },
    ie: {
        title: 'Éire',
        ccc: '+353',
        flag: '🇮🇪',
        translations: { en: 'Ireland', ar: 'أيرلندا' },
    },
    sv: {
        title: 'El Salvador',
        ccc: '+503',
        flag: '🇸🇻',
        translations: { en: 'El Salvador', ar: 'السلفادور' },
    },
    es: {
        title: 'España',
        ccc: '+34',
        flag: '🇪🇸',
        translations: { en: 'Spain', ar: 'أسبانيا' },
    },
    fk: {
        title: 'Falkland Islands',
        ccc: '+500',
        flag: '🇫🇰',
        translations: { en: 'Falkland Islands', ar: 'جزر فوكلاند' },
    },
    fj: {
        title: 'Fiji',
        ccc: '+679',
        flag: '🇫🇯',
        translations: { en: 'Fiji', ar: 'فيجي' },
    },
    fo: {
        title: 'Føroyar',
        ccc: '+298',
        flag: '🇫🇴',
        translations: { en: 'Faroe Islands', ar: 'جزر فارو' },
    },
    fr: {
        title: 'France',
        ccc: '+33',
        flag: '🇫🇷',
        translations: { en: 'France', ar: 'فرنسا' },
    },
    ga: {
        title: 'Gabon',
        ccc: '+241',
        flag: '🇬🇦',
        translations: { en: 'Gabon', ar: 'الجابون' },
    },
    gm: {
        title: 'Gambia',
        ccc: '+220',
        flag: '🇬🇲',
        translations: { en: 'Gambia', ar: 'غامبيا' },
    },
    gh: {
        title: 'Ghana',
        ccc: '+233',
        flag: '🇬🇭',
        translations: { en: 'Ghana', ar: 'غانا' },
    },
    gi: {
        title: 'Gibraltar',
        ccc: '+350',
        flag: '🇬🇮',
        translations: { en: 'Gibraltar', ar: 'جبل طارق' },
    },
    gd: {
        title: 'Grenada',
        ccc: '+1473',
        flag: '🇬🇩',
        translations: { en: 'Grenada', ar: 'جرينادا' },
    },
    gp: {
        title: 'Guadeloupe',
        ccc: '+590',
        flag: '🇬🇵',
        translations: { en: 'Guadeloupe', ar: 'جوادلوب' },
    },
    gu: {
        title: 'Guam',
        ccc: '+1671',
        flag: '🇬🇺',
        translations: { en: 'Guam', ar: 'جوام' },
    },
    gt: {
        title: 'Guatemala',
        ccc: '+502',
        flag: '🇬🇹',
        translations: { en: 'Guatemala', ar: 'جواتيمالا' },
    },
    gw: {
        title: 'Guiné-Bissau',
        ccc: '+245',
        flag: '🇬🇼',
        translations: { en: 'Guinea-Bissau', ar: 'غينيا بيساو' },
    },
    gq: {
        title: 'Guinea Ecuatorial',
        ccc: '+240',
        flag: '🇬🇶',
        translations: { en: 'Equatorial Guinea', ar: 'غينيا الاستوائية' },
    },
    gn: {
        title: 'Guinée',
        ccc: '+224',
        flag: '🇬🇳',
        translations: { en: 'Guinea', ar: 'غينيا' },
    },
    gy: {
        title: 'Guyana',
        ccc: '+592',
        flag: '🇬🇾',
        translations: { en: 'Guyana', ar: 'غيانا' },
    },
    gf: {
        title: 'Guyane française',
        ccc: '+594',
        flag: '🇬🇫',
        translations: { en: 'French Guiana', ar: 'غويانا' },
    },
    ht: {
        title: 'Haïti',
        ccc: '+509',
        flag: '🇭🇹',
        translations: { en: 'Haiti', ar: 'هايتي' },
    },
    hn: {
        title: 'Honduras',
        ccc: '+504',
        flag: '🇭🇳',
        translations: { en: 'Honduras', ar: 'هندوراس' },
    },
    hr: {
        title: 'Hrvatska',
        ccc: '+385',
        flag: '🇭🇷',
        translations: { en: 'Croatia', ar: 'كرواتيا' },
    },
    id: {
        title: 'Indonesia',
        ccc: '+62',
        flag: '🇮🇩',
        translations: { en: 'Indonesia', ar: 'اندونيسيا' },
    },
    is: {
        title: 'Ísland',
        ccc: '+354',
        flag: '🇮🇸',
        translations: { en: 'Iceland', ar: 'أيسلندا' },
    },
    it: {
        title: 'Italia',
        ccc: '+39',
        flag: '🇮🇹',
        translations: { en: 'Italy', ar: 'ايطاليا' },
    },
    jm: {
        title: 'Jamaica',
        ccc: '+1876',
        flag: '🇯🇲',
        translations: { en: 'Jamaica', ar: 'جامايكا' },
    },
    gl: {
        title: 'Kalaallit Nunaat',
        ccc: '+299',
        flag: '🇬🇱',
        translations: { en: 'Greenland', ar: 'جرينلاند' },
    },
    kh: {
        title: 'Kâmpŭchéa',
        ccc: '+855',
        flag: '🇰🇭',
        translations: { en: 'Cambodia', ar: 'كمبوديا' },
    },
    ke: {
        title: 'Kenya',
        ccc: '+254',
        flag: '🇰🇪',
        translations: { en: 'Kenya', ar: 'كينيا' },
    },
    ki: {
        title: 'Kiribati',
        ccc: '+686',
        flag: '🇰🇮',
        translations: { en: 'Kiribati', ar: 'كيريباتي' },
    },
    cf: {
        title: 'Ködörösêse tî Bêafrîka',
        ccc: '+236',
        flag: '🇨🇫',
        translations: {
            en: 'Central African Republic',
            ar: 'جمهورية افريقيا الوسطى',
        },
    },
    km: {
        title: 'Komori',
        ccc: '+269',
        flag: '🇰🇲',
        translations: { en: 'Comoros', ar: 'جزر القمر' },
    },
    re: {
        title: 'La Réunion',
        ccc: '+262',
        flag: '🇷🇪',
        translations: { en: 'Réunion', ar: 'روينيون' },
    },
    lv: {
        title: 'Latvija',
        ccc: '+371',
        flag: '🇱🇻',
        translations: { en: 'Latvia', ar: 'لاتفيا' },
    },
    ls: {
        title: 'Lesotho',
        ccc: '+266',
        flag: '🇱🇸',
        translations: { en: 'Lesotho', ar: 'ليسوتو' },
    },
    lr: {
        title: 'Liberia',
        ccc: '+231',
        flag: '🇱🇷',
        translations: { en: 'Liberia', ar: 'ليبيريا' },
    },
    li: {
        title: 'Liechtenstein',
        ccc: '+423',
        flag: '🇱🇮',
        translations: { en: 'Liechtenstein', ar: 'ليختنشتاين' },
    },
    lt: {
        title: 'Lietuva',
        ccc: '+370',
        flag: '🇱🇹',
        translations: { en: 'Lithuania', ar: 'ليتوانيا' },
    },
    lu: {
        title: 'Luxembourg',
        ccc: '+352',
        flag: '🇱🇺',
        translations: { en: 'Luxembourg', ar: 'لوكسمبورج' },
    },
    mg: {
        title: 'Madagasikara',
        ccc: '+261',
        flag: '🇲🇬',
        translations: { en: 'Madagascar', ar: 'مدغشقر' },
    },
    hu: {
        title: 'Magyarország',
        ccc: '+36',
        flag: '🇭🇺',
        translations: { en: 'Hungary', ar: 'المجر' },
    },
    mh: {
        title: 'M̧ajeļ',
        ccc: '+692',
        flag: '🇲🇭',
        translations: { en: 'Marshall Islands', ar: 'جزر المارشال' },
    },
    mw: {
        title: 'Malawi',
        ccc: '+265',
        flag: '🇲🇼',
        translations: { en: 'Malawi', ar: 'ملاوي' },
    },
    my: {
        title: 'Malaysia',
        ccc: '+60',
        flag: '🇲🇾',
        translations: { en: 'Malaysia', ar: 'ماليزيا' },
    },
    mv: {
        title: 'Maldives',
        ccc: '+960',
        flag: '🇲🇻',
        translations: { en: 'Maldives', ar: 'جزر الملديف' },
    },
    ml: {
        title: 'Mali',
        ccc: '+223',
        flag: '🇲🇱',
        translations: { en: 'Mali', ar: 'مالي' },
    },
    mt: {
        title: 'Malta',
        ccc: '+356',
        flag: '🇲🇹',
        translations: { en: 'Malta', ar: 'مالطا' },
    },
    mq: {
        title: 'Martinique',
        ccc: '+596',
        flag: '🇲🇶',
        translations: { en: 'Martinique', ar: 'مارتينيك' },
    },
    mu: {
        title: 'Maurice',
        ccc: '+230',
        flag: '🇲🇺',
        translations: { en: 'Mauritius', ar: 'موريشيوس' },
    },
    yt: {
        title: 'Mayotte',
        ccc: '+262',
        flag: '🇾🇹',
        translations: { en: 'Mayotte', ar: 'مايوت' },
    },
    mx: {
        title: 'México',
        ccc: '+52',
        flag: '🇲🇽',
        translations: { en: 'Mexico', ar: 'المكسيك' },
    },
    fm: {
        title: 'Micronesia',
        ccc: '+691',
        flag: '🇫🇲',
        translations: { en: 'Micronesia', ar: 'ميكرونيزيا' },
    },
    mz: {
        title: 'Moçambique',
        ccc: '+258',
        flag: '🇲🇿',
        translations: { en: 'Mozambique', ar: 'موزمبيق' },
    },
    md: {
        title: 'Moldova',
        ccc: '+373',
        flag: '🇲🇩',
        translations: { en: 'Moldova', ar: 'مولدافيا' },
    },
    mc: {
        title: 'Monaco',
        ccc: '+377',
        flag: '🇲🇨',
        translations: { en: 'Monaco', ar: 'موناكو' },
    },
    ms: {
        title: 'Montserrat',
        ccc: '+1664',
        flag: '🇲🇸',
        translations: { en: 'Montserrat', ar: 'مونتسرات' },
    },
    mm: {
        title: 'Myanma',
        ccc: '+95',
        flag: '🇲🇲',
        translations: { en: 'Myanmar', ar: 'ميانمار' },
    },
    na: {
        title: 'Namibia',
        ccc: '+264',
        flag: '🇳🇦',
        translations: { en: 'Namibia', ar: 'ناميبيا' },
    },
    nr: {
        title: 'Nauru',
        ccc: '+674',
        flag: '🇳🇷',
        translations: { en: 'Nauru', ar: 'نورو' },
    },
    nl: {
        title: 'Nederland',
        ccc: '+31',
        flag: '🇳🇱',
        translations: { en: 'Netherlands', ar: 'هولندا' },
    },
    bn: {
        title: 'Negara Brunei Darussalam',
        ccc: '+673',
        flag: '🇧🇳',
        translations: { en: 'Brunei', ar: 'بروناي' },
    },
    nz: {
        title: 'New Zealand',
        ccc: '+64',
        flag: '🇳🇿',
        translations: { en: 'New Zealand', ar: 'نيوزيلاندا' },
    },
    ni: {
        title: 'Nicaragua',
        ccc: '+505',
        flag: '🇳🇮',
        translations: { en: 'Nicaragua', ar: 'نيكاراجوا' },
    },
    ne: {
        title: 'Niger',
        ccc: '+227',
        flag: '🇳🇪',
        translations: { en: 'Niger', ar: 'النيجر' },
    },
    ng: {
        title: 'Nigeria',
        ccc: '+234',
        flag: '🇳🇬',
        translations: { en: 'Nigeria', ar: 'نيجيريا' },
    },
    nu: {
        title: 'Niuē',
        ccc: '+683',
        flag: '🇳🇺',
        translations: { en: 'Niue', ar: 'نيوي' },
    },
    nf: {
        title: 'Norfolk Island',
        ccc: '+672',
        flag: '🇳🇫',
        translations: { en: 'Norfolk Island', ar: 'جزيرة نورفوك' },
    },
    no: {
        title: 'Norge',
        ccc: '+47',
        flag: '🇳🇴',
        translations: { en: 'Norway', ar: 'النرويج' },
    },
    mp: {
        title: 'Northern Mariana Islands',
        ccc: '+1670',
        flag: '🇲🇵',
        translations: {
            en: 'Northern Mariana Islands',
            ar: 'جزر ماريانا الشمالية',
        },
    },
    nc: {
        title: 'Nouvelle-Calédonie',
        ccc: '+687',
        flag: '🇳🇨',
        translations: { en: 'New Caledonia', ar: 'كاليدونيا الجديدة' },
    },
    at: {
        title: 'Österreich',
        ccc: '+43',
        flag: '🇦🇹',
        translations: { en: 'Austria', ar: 'النمسا' },
    },
    uz: {
        title: 'O‘zbekiston',
        ccc: '+998',
        flag: '🇺🇿',
        translations: { en: 'Uzbekistan', ar: 'أوزبكستان' },
    },
    pk: {
        title: 'Pakistan',
        ccc: '+92',
        flag: '🇵🇰',
        translations: { en: 'Pakistan', ar: 'باكستان' },
    },
    pw: {
        title: 'Palau',
        ccc: '+680',
        flag: '🇵🇼',
        translations: { en: 'Palau', ar: 'بالاو' },
    },
    pa: {
        title: 'Panamá',
        ccc: '+507',
        flag: '🇵🇦',
        translations: { en: 'Panama', ar: 'بنما' },
    },
    pg: {
        title: 'Papua Niugini',
        ccc: '+675',
        flag: '🇵🇬',
        translations: { en: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' },
    },
    py: {
        title: 'Paraguay',
        ccc: '+595',
        flag: '🇵🇾',
        translations: { en: 'Paraguay', ar: 'باراجواي' },
    },
    pe: {
        title: 'Perú',
        ccc: '+51',
        flag: '🇵🇪',
        translations: { en: 'Peru', ar: 'بيرو' },
    },
    ph: {
        title: 'Pilipinas',
        ccc: '+63',
        flag: '🇵🇭',
        translations: { en: 'Philippines', ar: 'الفيلبين' },
    },
    pn: {
        title: 'Pitcairn Islands',
        ccc: '+64',
        flag: '🇵🇳',
        translations: { en: 'Pitcairn Islands', ar: 'بتكايرن' },
    },
    pl: {
        title: 'Polska',
        ccc: '+48',
        flag: '🇵🇱',
        translations: { en: 'Poland', ar: 'بولندا' },
    },
    pf: {
        title: 'Polynésie française',
        ccc: '+689',
        flag: '🇵🇫',
        translations: { en: 'French Polynesia', ar: 'بولينيزيا الفرنسية' },
    },
    pt: {
        title: 'Portugal',
        ccc: '+351',
        flag: '🇵🇹',
        translations: { en: 'Portugal', ar: 'البرتغال' },
    },
    do: {
        title: 'República Dominicana',
        ccc: '+18',
        flag: '🇩🇴',
        translations: { en: 'Dominican Republic', ar: 'جمهورية الدومينيك' },
    },
    xk: {
        title: 'Republika e Kosovës',
        ccc: '+383',
        flag: '🇽🇰',
        translations: { en: 'Kosovo', ar: 'كوسوفو' },
    },
    cd: {
        title: 'République démocratique du Congo',
        ccc: '+243',
        flag: '🇨🇩',
        translations: { en: 'DR Congo', ar: 'جمهورية الكونغو الديمقراطية' },
    },
    cg: {
        title: 'République du Congo',
        ccc: '+242',
        flag: '🇨🇬',
        translations: { en: 'Republic of the Congo', ar: 'الكونغو - برازافيل' },
    },
    ro: {
        title: 'România',
        ccc: '+40',
        flag: '🇷🇴',
        translations: { en: 'Romania', ar: 'رومانيا' },
    },
    rw: {
        title: 'Rwanda',
        ccc: '+250',
        flag: '🇷🇼',
        translations: { en: 'Rwanda', ar: 'رواندا' },
    },
    sh: {
        title: 'Saint Helena',
        ccc: '+2',
        flag: '🇸🇭',
        translations: {
            en: 'Saint Helena, Ascension and Tristan da Cunha',
            ar: 'سانت هيلنا',
        },
    },
    kn: {
        title: 'Saint Kitts and Nevis',
        ccc: '+1869',
        flag: '🇰🇳',
        translations: { en: 'Saint Kitts and Nevis', ar: 'سانت كيتس ونيفيس' },
    },
    lc: {
        title: 'Saint Lucia',
        ccc: '+1758',
        flag: '🇱🇨',
        translations: { en: 'Saint Lucia', ar: 'سانت لوسيا' },
    },
    vc: {
        title: 'Saint Vincent and the Grenadines',
        ccc: '+1784',
        flag: '🇻🇨',
        translations: {
            en: 'Saint Vincent and the Grenadines',
            ar: 'سانت فنسنت وغرنادين',
        },
    },
    bl: {
        title: 'Saint-Barthélemy',
        ccc: '+590',
        flag: '🇧🇱',
        translations: { en: 'Saint Barthélemy', ar: 'سان بارتيلمي' },
    },
    mf: {
        title: 'Saint-Martin',
        ccc: '+590',
        flag: '🇲🇫',
        translations: { en: 'Saint Martin', ar: 'سانت مارتين' },
    },
    pm: {
        title: 'Saint-Pierre-et-Miquelon',
        ccc: '+508',
        flag: '🇵🇲',
        translations: { en: 'Saint Pierre and Miquelon', ar: 'سانت بيير وميكولون' },
    },
    ws: {
        title: 'Samoa',
        ccc: '+685',
        flag: '🇼🇸',
        translations: { en: 'Samoa', ar: 'ساموا' },
    },
    sm: {
        title: 'San Marino',
        ccc: '+378',
        flag: '🇸🇲',
        translations: { en: 'San Marino', ar: 'سان مارينو' },
    },
    va: {
        title: 'Sancta Sedes',
        ccc: '+3',
        flag: '🇻🇦',
        translations: { en: 'Vatican City', ar: 'الفاتيكان' },
    },
    st: {
        title: 'São Tomé e Príncipe',
        ccc: '+239',
        flag: '🇸🇹',
        translations: { en: 'São Tomé and Príncipe', ar: 'ساو تومي وبرينسيبي' },
    },
    ch: {
        title: 'Schweiz',
        ccc: '+41',
        flag: '🇨🇭',
        translations: { en: 'Switzerland', ar: 'سويسرا' },
    },
    sn: {
        title: 'Sénégal',
        ccc: '+221',
        flag: '🇸🇳',
        translations: { en: 'Senegal', ar: 'السنغال' },
    },
    sc: {
        title: 'Seychelles',
        ccc: '+248',
        flag: '🇸🇨',
        translations: { en: 'Seychelles', ar: 'سيشل' },
    },
    al: {
        title: 'Shqipëria',
        ccc: '+355',
        flag: '🇦🇱',
        translations: { en: 'Albania', ar: 'ألبانيا' },
    },
    sl: {
        title: 'Sierra Leone',
        ccc: '+232',
        flag: '🇸🇱',
        translations: { en: 'Sierra Leone', ar: 'سيراليون' },
    },
    sg: {
        title: 'Singapore',
        ccc: '+65',
        flag: '🇸🇬',
        translations: { en: 'Singapore', ar: 'سنغافورة' },
    },
    sx: {
        title: 'Sint Maarten',
        ccc: '+1721',
        flag: '🇸🇽',
        translations: { en: 'Sint Maarten', ar: 'سينت مارتن' },
    },
    si: {
        title: 'Slovenija',
        ccc: '+386',
        flag: '🇸🇮',
        translations: { en: 'Slovenia', ar: 'سلوفينيا' },
    },
    sk: {
        title: 'Slovensko',
        ccc: '+421',
        flag: '🇸🇰',
        translations: { en: 'Slovakia', ar: 'سلوفاكيا' },
    },
    sb: {
        title: 'Solomon Islands',
        ccc: '+677',
        flag: '🇸🇧',
        translations: { en: 'Solomon Islands', ar: 'جزر سليمان' },
    },
    so: {
        title: 'Soomaaliya',
        ccc: '+252',
        flag: '🇸🇴',
        translations: { en: 'Somalia', ar: 'الصومال' },
    },
    za: {
        title: 'South Africa',
        ccc: '+27',
        flag: '🇿🇦',
        translations: { en: 'South Africa', ar: 'جمهورية جنوب افريقيا' },
    },
    gs: {
        title: 'South Georgia',
        ccc: '+500',
        flag: '🇬🇸',
        translations: {
            en: 'South Georgia',
            ar: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
        },
    },
    ss: {
        title: 'South Sudan',
        ccc: '+211',
        flag: '🇸🇸',
        translations: { en: 'South Sudan', ar: 'جنوب السودان' },
    },
    fi: {
        title: 'Suomi',
        ccc: '+358',
        flag: '🇫🇮',
        translations: { en: 'Finland', ar: 'فنلندا' },
    },
    sr: {
        title: 'Suriname',
        ccc: '+597',
        flag: '🇸🇷',
        translations: { en: 'Suriname', ar: 'سورينام' },
    },
    sj: {
        title: 'Svalbard og Jan Mayen',
        ccc: '+4779',
        flag: '🇸🇯',
        translations: { en: 'Svalbard and Jan Mayen', ar: 'سفالبارد وجان مايان' },
    },
    se: {
        title: 'Sverige',
        ccc: '+46',
        flag: '🇸🇪',
        translations: { en: 'Sweden', ar: 'السويد' },
    },
    sz: {
        title: 'Swaziland',
        ccc: '+268',
        flag: '🇸🇿',
        translations: { en: 'Eswatini', ar: 'سوازيلاند' },
    },
    tz: {
        title: 'Tanzania',
        ccc: '+255',
        flag: '🇹🇿',
        translations: { en: 'Tanzania', ar: 'تانزانيا' },
    },
    td: {
        title: 'Tchad',
        ccc: '+235',
        flag: '🇹🇩',
        translations: { en: 'Chad', ar: 'تشاد' },
    },
    tf: {
        title: 'Territoire des Terres australes et antarctiques françaises',
        ccc: '+262',
        flag: '🇹🇫',
        translations: {
            en: 'French Southern and Antarctic Lands',
            ar: 'المقاطعات الجنوبية الفرنسية',
        },
    },
    tl: {
        title: 'Timor-Leste',
        ccc: '+670',
        flag: '🇹🇱',
        translations: { en: 'Timor-Leste', ar: 'تيمور الشرقية' },
    },
    tg: {
        title: 'Togo',
        ccc: '+228',
        flag: '🇹🇬',
        translations: { en: 'Togo', ar: 'توجو' },
    },
    tk: {
        title: 'Tokelau',
        ccc: '+690',
        flag: '🇹🇰',
        translations: { en: 'Tokelau', ar: 'توكيلو' },
    },
    to: {
        title: 'Tonga',
        ccc: '+676',
        flag: '🇹🇴',
        translations: { en: 'Tonga', ar: 'تونجا' },
    },
    tr: {
        title: 'Türkiye',
        ccc: '+90',
        flag: '🇹🇷',
        translations: { en: 'Turkey', ar: 'تركيا' },
    },
    tm: {
        title: 'Türkmenistan',
        ccc: '+993',
        flag: '🇹🇲',
        translations: { en: 'Turkmenistan', ar: 'تركمانستان' },
    },
    tc: {
        title: 'Turks and Caicos Islands',
        ccc: '+1649',
        flag: '🇹🇨',
        translations: { en: 'Turks and Caicos Islands', ar: 'جزر الترك وجايكوس' },
    },
    tv: {
        title: 'Tuvalu',
        ccc: '+688',
        flag: '🇹🇻',
        translations: { en: 'Tuvalu', ar: 'توفالو' },
    },
    ug: {
        title: 'Uganda',
        ccc: '+256',
        flag: '🇺🇬',
        translations: { en: 'Uganda', ar: 'أوغندا' },
    },
    gb: {
        title: 'United Kingdom',
        ccc: '+44',
        flag: '🇬🇧',
        translations: { en: 'United Kingdom', ar: 'المملكة المتحدة' },
    },
    us: {
        title: 'United States',
        ccc: '+1',
        flag: '🇺🇸',
        translations: { en: 'United States', ar: 'الولايات المتحدة الأمريكية' },
    },
    um: {
        title: 'United States Minor Outlying Islands',
        ccc: '+268',
        flag: '🇺🇲',
        translations: {
            en: 'United States Minor Outlying Islands',
            ar: 'جزر الولايات المتحدة البعيدة الصغيرة',
        },
    },
    uy: {
        title: 'Uruguay',
        ccc: '+598',
        flag: '🇺🇾',
        translations: { en: 'Uruguay', ar: 'أورجواي' },
    },
    vu: {
        title: 'Vanuatu',
        ccc: '+678',
        flag: '🇻🇺',
        translations: { en: 'Vanuatu', ar: 'فانواتو' },
    },
    ve: {
        title: 'Venezuela',
        ccc: '+58',
        flag: '🇻🇪',
        translations: { en: 'Venezuela', ar: 'فنزويلا' },
    },
    vi: {
        title: 'Virgin Islands of the United States',
        ccc: '+1340',
        flag: '🇻🇮',
        translations: {
            en: 'United States Virgin Islands',
            ar: 'جزر فرجين الأمريكية',
        },
    },
    vn: {
        title: 'Việt Nam',
        ccc: '+84',
        flag: '🇻🇳',
        translations: { en: 'Vietnam', ar: 'فيتنام' },
    },
    wf: {
        title: 'Wallis et Futuna',
        ccc: '+681',
        flag: '🇼🇫',
        translations: { en: 'Wallis and Futuna', ar: 'جزر والس وفوتونا' },
    },
    zm: {
        title: 'Zambia',
        ccc: '+260',
        flag: '🇿🇲',
        translations: { en: 'Zambia', ar: 'زامبيا' },
    },
    zw: {
        title: 'Zimbabwe',
        ccc: '+263',
        flag: '🇿🇼',
        translations: { en: 'Zimbabwe', ar: 'زيمبابوي' },
    },
    lk: {
        title: 'śrī laṃkāva',
        ccc: '+94',
        flag: '🇱🇰',
        translations: { en: 'Sri Lanka', ar: 'سريلانكا' },
    },
    bt: {
        title: 'ʼbrug-yul',
        ccc: '+975',
        flag: '🇧🇹',
        translations: { en: 'Bhutan', ar: 'بوتان' },
    },
    gr: {
        title: 'Ελλάδα',
        ccc: '+30',
        flag: '🇬🇷',
        translations: { en: 'Greece', ar: 'اليونان' },
    },
    cy: {
        title: 'Κύπρος',
        ccc: '+357',
        flag: '🇨🇾',
        translations: { en: 'Cyprus', ar: 'قبرص' },
    },
    by: {
        title: 'Белару́сь',
        ccc: '+375',
        flag: '🇧🇾',
        translations: { en: 'Belarus', ar: 'روسيا البيضاء' },
    },
    bg: {
        title: 'България',
        ccc: '+359',
        flag: '🇧🇬',
        translations: { en: 'Bulgaria', ar: 'بلغاريا' },
    },
    kg: {
        title: 'Кыргызстан',
        ccc: '+996',
        flag: '🇰🇬',
        translations: { en: 'Kyrgyzstan', ar: 'قرغيزستان' },
    },
    mk: {
        title: 'Македонија',
        ccc: '+389',
        flag: '🇲🇰',
        translations: { en: 'North Macedonia', ar: 'مقدونيا' },
    },
    mn: {
        title: 'Монгол улс',
        ccc: '+976',
        flag: '🇲🇳',
        translations: { en: 'Mongolia', ar: 'منغوليا' },
    },
    ru: {
        title: 'Россия',
        ccc: '+7',
        flag: '🇷🇺',
        translations: { en: 'Russia', ar: 'روسيا' },
    },
    rs: {
        title: 'Србија',
        ccc: '+381',
        flag: '🇷🇸',
        translations: { en: 'Serbia', ar: 'صربيا' },
    },
    tj: {
        title: 'Тоҷикистон',
        ccc: '+992',
        flag: '🇹🇯',
        translations: { en: 'Tajikistan', ar: 'طاجكستان' },
    },
    ua: {
        title: 'Україна',
        ccc: '+380',
        flag: '🇺🇦',
        translations: { en: 'Ukraine', ar: 'أوكرانيا' },
    },
    me: {
        title: 'Црна Гора',
        ccc: '+382',
        flag: '🇲🇪',
        translations: { en: 'Montenegro', ar: 'الجبل الأسود' },
    },
    kz: {
        title: 'Қазақстан',
        ccc: '+7',
        flag: '🇰🇿',
        translations: { en: 'Kazakhstan', ar: 'كازاخستان' },
    },
    am: {
        title: 'Հայաստան',
        ccc: '+374',
        flag: '🇦🇲',
        translations: { en: 'Armenia', ar: 'أرمينيا' },
    },
    il: {
        title: 'יִשְׂרָאֵל',
        ccc: '+972',
        flag: '🇮🇱',
        translations: { en: 'Israel', ar: 'اسرائيل' },
    },
    af: {
        title: 'افغانستان',
        ccc: '+93',
        flag: '🇦🇫',
        translations: { en: 'Afghanistan', ar: 'أفغانستان' },
    },
    jo: {
        title: 'الأردن',
        ccc: '+962',
        flag: '🇯🇴',
        translations: { en: 'Jordan', ar: 'الأردن' },
    },
    dz: {
        title: 'الجزائر',
        ccc: '+213',
        flag: '🇩🇿',
        translations: { en: 'Algeria', ar: 'الجزائر' },
    },
    sd: {
        title: 'السودان',
        ccc: '+249',
        flag: '🇸🇩',
        translations: { en: 'Sudan', ar: 'السودان' },
    },

    iq: {
        title: 'العراق',
        ccc: '+964',
        flag: '🇮🇶',
        translations: { en: 'Iraq', ar: 'العراق' },
    },
    sa: {
        title: 'العربية السعودية',
        ccc: '+966',
        flag: '🇸🇦',
        translations: { en: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
    },
    kw: {
        title: 'الكويت',
        ccc: '+965',
        flag: '🇰🇼',
        translations: { en: 'Kuwait', ar: 'الكويت' },
    },
    ma: {
        title: 'المغرب',
        ccc: '+212',
        flag: '🇲🇦',
        translations: { en: 'Morocco', ar: 'المغرب' },
    },
    tn: {
        title: 'تونس',
        ccc: '+216',
        flag: '🇹🇳',
        translations: { en: 'Tunisia', ar: 'تونس' },
    },
    ae: {
        title: 'دولة الإمارات العربية المتحدة',
        ccc: '+971',
        flag: '🇦🇪',
        translations: {
            en: 'United Arab Emirates',
            ar: 'الامارات العربية المتحدة',
        },
    },
    om: {
        title: 'عمان',
        ccc: '+968',
        flag: '🇴🇲',
        translations: { en: 'Oman', ar: 'عمان' },
    },
    ps: {
        title: 'فلسطين',
        ccc: '+970',
        flag: '🇵🇸',
        translations: { en: 'Palestine', ar: 'فلسطين' },
    },
    lb: {
        title: 'لبنان',
        ccc: '+961',
        flag: '🇱🇧',
        translations: { en: 'Lebanon', ar: 'لبنان' },
    },
    eg: {
        title: 'مصر‎',
        ccc: '+20',
        flag: '🇪🇬',
        translations: { en: 'Egypt', ar: 'مصر' },
    },
    mr: {
        title: 'موريتانيا',
        ccc: '+222',
        flag: '🇲🇷',
        translations: { en: 'Mauritania', ar: 'موريتانيا' },
    },
    np: {
        title: 'नेपाल',
        ccc: '+977',
        flag: '🇳🇵',
        translations: { en: 'Nepal', ar: 'نيبال' },
    },
    in: {
        title: 'भारत',
        ccc: '+91',
        flag: '🇮🇳',
        translations: { en: 'India', ar: 'الهند' },
    },
    th: {
        title: 'ประเทศไทย',
        ccc: '+66',
        flag: '🇹🇭',
        translations: { en: 'Thailand', ar: 'تايلند' },
    },
    la: {
        title: 'ສປປລາວ',
        ccc: '+856',
        flag: '🇱🇦',
        translations: { en: 'Laos', ar: 'لاوس' },
    },
    ge: {
        title: 'საქართველო',
        ccc: '+995',
        flag: '🇬🇪',
        translations: { en: 'Georgia', ar: 'جورجيا' },
    },
    et: {
        title: 'ኢትዮጵያ',
        ccc: '+251',
        flag: '🇪🇹',
        translations: { en: 'Ethiopia', ar: 'اثيوبيا' },
    },
    er: {
        title: 'ኤርትራ',
        ccc: '+291',
        flag: '🇪🇷',
        translations: { en: 'Eritrea', ar: 'اريتريا' },
    },
    bh: {
        title: '‏البحرين',
        ccc: '+973',
        flag: '🇧🇭',
        translations: { en: 'Bahrain', ar: 'البحرين' },
    },
    ly: {
        title: '‏ليبيا',
        ccc: '+218',
        flag: '🇱🇾',
        translations: { en: 'Libya', ar: 'ليبيا' },
    },
    cn: {
        title: '中国',
        ccc: '+86',
        flag: '🇨🇳',
        translations: { en: 'China', ar: 'الصين' },
    },
    jp: {
        title: '日本',
        ccc: '+81',
        flag: '🇯🇵',
        translations: { en: 'Japan', ar: 'اليابان' },
    },
    mo: {
        title: '澳門',
        ccc: '+853',
        flag: '🇲🇴',
        translations: { en: 'Macau', ar: 'ماكاو الصينية' },
    },
    tw: {
        title: '臺灣',
        ccc: '+886',
        flag: '🇹🇼',
        translations: { en: 'Taiwan', ar: 'تايوان' },
    },
    hk: {
        title: '香港',
        ccc: '+852',
        flag: '🇭🇰',
        translations: { en: 'Hong Kong', ar: 'هونج كونج الصينية' },
    },
    kr: {
        title: '대한민국',
        ccc: '+82',
        flag: '🇰🇷',
        translations: { en: 'South Korea', ar: 'كوريا الجنوبية' },
    },
};
